# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75e550f5f83d49060dd335bb337af9f2"
name = "LatentSEO"
application_url = "https://latentseo.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks"

  # GDPR Mandatory Webhooks
  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://latentseo.fly.dev/auth/callback",
  "https://latentseo.fly.dev/auth/shopify/callback"
]
